### ISSUE TITLE
Access to wifi sta rssi value

### ISSUE THREAD

**Issue by ruimarinho** [OpenSprinkler/OpenSprinkler-Firmware#100]
Hi @rayshobby,

I do not see a way of accessing the rssi signal from the esp chip. This would be interesting to expose via the API so we can monitor more closely the wifi signal strength. A strength indicator could then be added to the frontend UI.

**Comment by rayshobby** [comment]
rssi is already exposed in the API:
https://openthings.freshdesk.com/support/solutions/articles/5000716363-os-api-documents
page 2 close to the top

**Comment by ruimarinho** [comment]
Awesome! I was looking at 2.1.7's pdf. Thanks!
