### ISSUE TITLE
Feature request: Time of year watering restrictions

### ISSUE THREAD

**Issue by mpfl** [OpenSprinkler/OpenSprinkler-Firmware#110]
In Western Australia we [are not permitted to use scheme water to water our gardens during winter](https://www.watercorporation.com.au/save-water/watering-days/winter-sprinkler-ban). It would be great to have the ability to automatically disable watering at certain times of year.

**Comment by alco28** [comment]
this should be nice!

**Comment by craigcarps** [comment]
I’d also be keen to see this enhancement

**Comment by SkullKill** [comment]
+1

linking this
https://opensprinkler.com/forums/topic/enable-disable-programs-via-a-range-of-dates/

**Comment by rayshobby** [comment]
This feature has been implemented in the upcoming firmware 2.2.0: for each program, it allows you to set a 'date range' (start date and end date) so that the program is only enabled during the date range.
