### ISSUE TITLE
OpenSprinkler::switch_httpstation causes crash under certain conditions

### ISSUE THREAD

**Issue by vk2tds** [OpenSprinkler/OpenSprinkler-Firmware#111]
I have located a bug in OpenSprinkler::switch_httpstation whereby it will cause a fatal exception if the 'server' is blank. I have developed a one line fix for this, that tests for 'cmd' or 'server' being null, and if so, do not run bf.emit_p

```
        if ((server != NULL) & (cmd != NULL)) // Do not run if either the command or server are NULL
                bf.emit_p(PSTR("GET /$S HTTP/1.0\r\nHOST: $S\r\n\r\n"), cmd, server);
```

**Comment by rayshobby** [comment]
ok, thanks. will integrate it into the firmware.

**Comment by rayshobby** [comment]
The fix has been integrated into the firmware, so I am closing this now. Thanks.
