### ISSUE TITLE
Device unique identifier 

### ISSUE THREAD

**Issue by travisghansen** [OpenSprinkler/OpenSprinkler-Firmware#124]
I’ve been working on the home assistant integration for opensprinkler and some sort of unique identifier available via the api would be great. I’m not sure if there’s some sort of serial number available in the hardware or even the mac address if nothing else could do.

Thanks for the consideration!

**Comment by xaque208** [comment]
There is some machine ID that you can reference I've seen in some other ESP projects.

**Comment by travisghansen** [comment]
Any chance we can get it exposed via the api(s)?

**Comment by psmedley** [comment]
It should be possible, opengarage exposes the Mac address via the api

**Comment by rayshobby** [comment]
This has been addressed in the upcoming firmware (not officially released yet), so I am closing this issue for now.
