### ISSUE TITLE
[Enhancement] Turn on stations scheduled to be on upon start-up and end of manual runs

### ISSUE THREAD

**Issue by denisfrench** [OpenSprinkler/OpenSprinkler-Firmware#14]
I get this is a bit tricky, but it would be helpful if stations scheduled to be already on as per their regular program were turned on upon start-up/reboot, and at the completion of manual runs.

This would assist recovery from power outages, and prevent manual runs from totally upsetting the originally scheduled programs.

**Comment by salbahra** [comment]
Ray is going to switch to a station queue system and I think if the queue is saved in EEPROM or another persistent location then it would accomplish this task.

**Comment by brecht1234** [comment]
Was this feature included in the 2.1.6 release?

**Comment by rayshobby** [comment]
No, this is not included in 2.1.6 release. At the moment it's not easy to resume a running program across reboot, because this requires non-volatile memory (such as FRAM) that can be reliably written many times. Doing so would require a hardware change.
