### ISSUE TITLE
Define a station as zone and http

### ISSUE THREAD

**Issue by opensprinklershop** [OpenSprinkler/OpenSprinkler-Firmware#144]
At the moment a station can be either http or zone. However, if you want to perform an action by opening and closing, you cannot combine this (so easily). A zone type station + http would make sense

**Comment by rayshobby** [comment]
I believe this is already done: any 'special zone' attribute is on top of a zone's standard behavior -- that is, the zone will physically turn on, and on top of that, if it's a HTTP zone, it will additionally send out HTTP command.
