### ISSUE TITLE
HTTP station receives "off" command repeatedly

### ISSUE THREAD

**Issue by xaque208** [OpenSprinkler/OpenSprinkler-Firmware#147]
Hello, I'm wondering if this is by design, or perhaps if there is a way to disable this.  I've noticed today that an HTTP station continues to receive whatever is in the "off" field of the HTTP station, and this appears to happen for each HTTP station I have.

Is there a way to disable this behavior I'm overlooking?  This becomes a problem when using the osbee as a remote http station, I'm unable to get above a minute of runtime due to the off command being called repeatedly.  I don't remember this being an issue last year, but now I'm wondering how long this has been happening.  Any guidance here would be appreciated.

Running 2.1.9 rev 4

**Comment by rayshobby** [comment]
Go to Edit Options -> Advanced -> uncheck "Special Station Auto Refresh".

**Comment by xaque208** [comment]
Amazing, thank you!
