### ISSUE TITLE
Firmware os_219_rev4 - grey screen

### ISSUE THREAD

**Issue by juanbrunette** [OpenSprinkler/OpenSprinkler-Firmware#148]
I am trying to update the device to Firmware os_219_rev4 - after I do it I get a login screen - once I type my password I just get a blank grey screen. If I downgrade to Firmware os_219_rev3 then it works fine again. Any pointers please - I really want to make use of the MQTT for my Home Assistant integration.

**Comment by rayshobby** [comment]
I just responded to you through support ticket. Here is what I said: What you have is TIAO controller, it is NOT OpenSprinkler. They are a clone of OpenSprinkler, they don't even acknowledge that their product is based on OpenSprinkler. It's unethical. Please seek support from them.
