### ISSUE TITLE
Weather Problem Display

### ISSUE THREAD

**Issue by PipeDeveloper** [OpenSprinkler/OpenSprinkler-Firmware#151]
Hello!

I have upgrade my opensprinkler on my Raspberry Pi (OSPi) to the version 2.1.9 (4). but it seems that the weather report have an issue. I dont know if is Dark Sky problem or the firmware.

<img src="https://user-images.githubusercontent.com/35433329/90479527-d3527b80-e0fc-11ea-8c45-4dc8e3454b20.PNG" width=300>

Im not sure if the card have a problem but also is not showing the location under the temperature. it seems bugged.

<img src="https://user-images.githubusercontent.com/35433329/90479606-ecf3c300-e0fc-11ea-9864-1bf8baf90fd7.png" width=450>

I double check my location setings and all seems to be setted.

**Comment by rayshobby** [comment]
I am not sure what's the cause -- the diagnosis says clearly that the connection failed. I don't know the reason but the weather service is up and running, perhaps it was a temporary issue?
