### ISSUE TITLE
Firmware compiled in debug mode since latest merge

### ISSUE THREAD

**Issue by maxgerhardt** [OpenSprinkler/OpenSprinkler-Firmware#164]
The latest merge has caused the change

https://github.com/OpenSprinkler/OpenSprinkler-Firmware/commit/2b9788145159a59ac0163c2154d208f2f6df478b#diff-b69c8b9733987541db4bd0812b8820aa6e3964427a232d486a4dff6f5e14f3c6R27

https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/443865d4b8d84c49b8949f99e7150ea770ab5e9c/defines.h#L26-L28

thus the firmware will be compiled in debug mode. 

That was kinda good because it revealed compile errors in code that was only enabled in debug mode (like, reading out some ethernet controller registers) but I'm wondering whether that change was intentional or just overlooked by the original author.

**Comment by rayshobby** [comment]
It was turned on by mistake. It's now commented out.
