### ISSUE TITLE
Azure IOT Hub MQTT Support

### ISSUE THREAD

**Issue by allanwright** [OpenSprinkler/OpenSprinkler-Firmware#166]
The maximum length of the username/password fields (32 characters) is too short to allow OpenSprinkler to connect to Azure IOT Hub using MQTT.

The username and password need to be in the following formats:
Username = {iothubhostname}/{device_id}/?api-version=2018-06-30
Password = SharedAccessSignature sig={signature-string}&se={expiry}&sr={URL-encoded-resourceURI}

With a one character IOT Hub name (that still make the entire hub name *azure-devices.net) and a one character device id, the minimum username length would be 45 characters.

I'd need to do some more research to find the lengths of a SAS Token, but from the example I've found [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support), it appears they would be in excess of 150 characters.

Given the low memory environment that the OpenSprinkler firmware is designed to run, it this something that could be changed in order to support Azure IOT hub, assuming also that there aren't other issues that I may not have considered yet.

**Comment by rayshobby** [comment]
The limit of 32 characters is a UI constraint -- the input boxes have a maxlength set to 32. The firmware does not particularly limit the username / password, although it does have a hard limit of 160 characters on each string option.
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/master/defines.h#L135
So if the password itself is going to be more than 150 characters, it won't work with the firmware. You can increase the string option size, and without the UI you can always use the OpenSprinkler HTTP API to set the mqtt parameters, so you are not constrained by the 32 character limit.
