### ISSUE TITLE
Vision and Non-goals?

### ISSUE THREAD

**Issue by StohanzlMart** [OpenSprinkler/OpenSprinkler-Firmware#167]
I love this idea and project and I'm wondering how to help it flourish!

I see smart farming (CEA) as a huge potential. If to adapt, OS would have to:

1. Organise orchestration reliably over (dedicated) os-rpi for os-esps -> gateway module?
2. Add custom_sensor mqtt case
3. "Dynamic" instantion, setup and use of possible I²C-sensors

I think a "gateway" module for rpi (with GSM and (solar) powermanagement) could work; alternatively a Mesh network?
The sensors are just I²C'd in, as seen in this [hardware example from closed source competitor](https://www.aquashieldcontrol.com/smart-hydroponics-and-aquaponics-with-aquashield-the-hardware-of-aquashield-under-the-hood/).

What do you think? Is OS just a little tool for one job, or can it stay modular and grow its ecosystem?

Maybe also relevant:
https://github.com/kizniche/Mycodo
https://github.com/SensorsIot/SuperPower

love

**Comment by rayshobby** [comment]
Honestly I think this is too ambitious for OpenSprinkler. The difficulty with integrating multiple sensors, particularly analog sensors, is how exactly the sensor values should affect the watering. Also, I would be careful depending too much on RPi -- there is an ongoing shortage of RPi which will probably last another couple of years.
