### ISSUE TITLE
Expose BSSID when in AP mode

### ISSUE THREAD

**Issue by ruimarinho** [OpenSprinkler/OpenSprinkler-Firmware#168]
Hi @rayshobby,

It would be great to display the BSSID of the network found when displaying the list of networks under AP mode. Currently, each AP for the same network name is displayed alongside a signal strength, but one has to deduce the correct AP according to its signal.

This assuming it is guaranteed that opensprinkler will use that specific AP, which in my case I don't think was the case.

Thanks,

**Comment by rayshobby** [comment]
This should be relatively easy to implement. It looks like ESP8266 core library does allow connection to a specific bssid if it's specified. I will put this on my todo list (though I don't have a mesh network so I will probably have to find someone to help test it).

**Comment by psmedley** [comment]
I can test this, I have a mesh network and an os3.0 at home.

**Comment by rayshobby** [comment]
We've released a test version of firmware 2.2.0(0), per forum post:
https://opensprinkler.com/forums/topic/first-version-of-firmware-2-2-0-ready-for-testing/

It has added support for saving BSSID and channel information. The related commit history is here:
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/commit/a5279a37e0cfc68880776fe21a91f864af7df04b

You can try it out to test. Thanks.
