### ISSUE TITLE
station delay always resets to 0

### ISSUE THREAD

**Issue by docsparks** [OpenSprinkler/OpenSprinkler-Firmware#177]
rpi, 2.1.9(4) 

delay between stations resets to 0 and never is applied after clicking save.

confirmed on two different rpis

to be clear:
9-Dot button > Edit Options > Station Handling  > Station Delay > Change to 5 > Click Submit

do it again to double check, back to 0.

**Comment by rayshobby** [comment]
First of all, please use the latest firmware 2.1.9(7) as older firmwares may no longer work with the current UI. Second, station delay is on granularity of 5 seconds. Any input smaller than 5 will be rounded to 0.

**Comment by docsparks** [comment]
I was wrong about the versioning, I do have the latest.    Was just typing off the top of my head.

Changing the number to 5 has seemed to fix the issue, Thanks.

**Comment by mode2k** [comment]
Why rounding to 5? Does it make sense?
