### ISSUE TITLE
Proposal: Programs with active window

### ISSUE THREAD

**Issue by Heimchen** [OpenSprinkler/OpenSprinkler-Firmware#179]
Hi,
I'm just starting with OS, because I'm planning my own irrigation project :-)
I have a robot lawn mower and thus I must ensure, that the irrigation system is never active, when robot is active. So I'm missing a program, which is only active in defined time windows. Thus also if weather increases runtime it is guaranteed, that the irrigation is never active, when my robot is activ. Currently I have to take care on my own, that the accumulated durations will never meet the active time of my robot. Additionally when using weather support, I have to reserve 2.5 times of the accumulated durations.
If I'm right this is a common feature of commercial irrigation controllers.

These are my ideas:
- Define multiple time windows including start time, end time and active days of week (opt).
- Define the runtime per interval/week for each zone (as it is).
- When window is entered, OS starts the next zone with pending runtime.
- When zone's runtime is completed, OS starts the next zone with pending runtime.
- If zone's runtime is longer than current window, it is limited to the current window and continued in next window.
- OS may take a configurable minimum runtime per zone into account. Since the runtime of a zone must ensure that the ground is irrigated deep enough, this prevents a program with runtime of 20min to be split into 2x10min due to the end of the current window. Also with configuring minimum runtime to 0% or 100% it is possible to disable this feature or prevent splitting of the runtime of a zone.

I would contribute the C++ code, but I need somebody who implements the app, since my last JavaScript experience was 20 years ago.

**Comment by rayshobby** [comment]
This is an interesting idea (I also started using a robot lawn mower last year. I generally water the lawn in the morning when it's not too hot and the lawn mower starts in the afternoon when the grass is relatively dry). But I am afraid this feature is too specific / specialized for the particular need. It's also going to make the UI complicated to explain for anyone who doesn't need this feature. So I think it's best to leave this as a personal project to customize the firmware and UI.
