### ISSUE TITLE
Progress in development?

### ISSUE THREAD

**Issue by rucksman** [OpenSprinkler/OpenSprinkler-Firmware#181]
Is there any progress in development for the firmware, especially for the MQTT part? I am somehow confused as the latest release is now 2.1.8 whereas I am using 2.1.9 (4) which was the latest version when I bought my OSPi.

**Comment by rayshobby** [comment]
We are slowly getting ready to release firmware 2.2.0, which uses EP8266 core 3.0.2 and will support OpenThingsCloud (OTC) for remote access. Unfortunately at this point firmware 2.2.0 doesn't include anything new regarding MQTT yet.
