### ISSUE TITLE
Proposal: Show OSPi analog input value next to the weather

### ISSUE THREAD

**Issue by opensprinklershop** [OpenSprinkler/OpenSprinkler-Firmware#183]
Idea: 
Show OSPi analog input values next to the weather (app+web interface)
For example, for a fill level indicator of a cistern or soil moisture
Display should be like a progress bar

What to do: Need an app configuration for that:
1. Give analog input names (no names - no display). Here for example "cistern"
2. Enter min+max values. For example, min=0.4 and max=3.4
3. Inverse: If min>max display is inverse

Showing like a progress bar: cistern [XXXX70%X......] (just an example, you can do it better!)

**Comment by rayshobby** [comment]
This is a request for OpenSprinkler-App, should be posted there.
