### ISSUE TITLE
Help: Saving/Restoring Station Attributes Data (Increased Bits Size - Bad Parse ??)

### ISSUE THREAD

**Issue by trbolexis** [OpenSprinkler/OpenSprinkler-Firmware#185]
I have modified the firmware code base (and app code base) to add additional master stations -> 8 Master Stations.

Everything works perfectly in operation, but the individual station attributes do no persist after a reboot. For example:

If I disable SXX and reboot the OS3.0 the station will be enabled again.
If I set a ignore rain delay, and ignore sensor 2 on SXX the options are then deselected after reboot.

I get the feeling that the memory space for the station attributes is a specific size, and the new data is not saving correctly to SPIFFS (or wherever), and not restoring on power up. Possibly the data is saving corectly, but not being parsed properly by the firmware? I am not sure how to debug this.

Can someone point me in the correct direction to remedy this? Thank you.

![image](https://user-images.githubusercontent.com/36283021/123495597-3fcdbf00-d5d9-11eb-9ac8-0c78d0a1489a.png)
![image](https://user-images.githubusercontent.com/36283021/123495613-4eb47180-d5d9-11eb-80b8-5eb7bcbb1b35.png)
![image](https://user-images.githubusercontent.com/36283021/123495625-58d67000-d5d9-11eb-9241-264a2297b92e.png)

**Comment by docsparks** [comment]
did you resolve this?  any chances to share where you changed?

**Comment by rayshobby** [comment]
Can you post the changes you made somewhere? It's difficult to reason about the issue without seeing the code.
