### ISSUE TITLE
Open sprinkler collision with uart 

### ISSUE THREAD

**Issue by ilouzl** [OpenSprinkler/OpenSprinkler-Firmware#192]
I noticed that as long as open sprinkler service is active, the serial (uart) console is unavailable, or to be more specific - writing (tx) is unavailable.
I refer to the default uart pins at GPIO 14 & 15.
Is that a coincidence?

**Comment by rayshobby** [comment]
I am not sure how to solve this issue -- if you use RPi, generally you can use printf to print out information. There is no need to rely on the hardware serial.
