### ISSUE TITLE
Rasperry Pi OS 64BIt Compatiblity?

### ISSUE THREAD

**Issue by mathesst** [OpenSprinkler/OpenSprinkler-Firmware#198]
Hi,

just read that there is now a 64BIt Image with ARMv8 Arch support and my question is, is OSPI compatible?

https://www.raspberrypi.com/news/raspberry-pi-os-64-bit/ 

BG Mathias

**Comment by kpfleming** [comment]
It works on my Debian aarch64 installations running on Pi3B boards, so there's no reason it would not work on Raspberry Pi OS aarch64.

**Comment by mathesst** [comment]
Great! Then I will close this thing!

Thanks @kpfleming !
