### ISSUE TITLE
OpenSprinkler does not appear to honor DHCP T1/T2 timers

### ISSUE THREAD

**Issue by the-maldridge** [OpenSprinkler/OpenSprinkler-Firmware#204]
I have my opensprinkler plugged in via ethernet to a particular zone where it pulls down a DHCP lease.  This lease has relatively short but still in-spec lifetime parameters.  Over time, I notice that the OpenSprinkler has kept the IP even though it has failed to renew it with DHCP causing the address to be dropped out of the lease table.

This feels like a bug, but with my limited knowledge of the firmware I can't point to where.

**Comment by rayshobby** [comment]
The firmware uses the standard ESP8266 library (and in the case of wired Ethernet, either EthernetENC or UIPEthernet library). So the DHCP issue would be an issue with these libraries. This isn't something we have control over. You could submit a ticket to the github repo of the corresponding library.
