### ISSUE TITLE
[Feature Request] Sleep the hardware display (OLED develops severe burn-in)

### ISSUE THREAD

**Issue by Nu11u5** [OpenSprinkler/OpenSprinkler-Firmware#206]
I have the OpenSprinkler hardware operating for a few years now, and the OLED display has severe burn-in and is unreadable in areas.  It may need to be replaced if I am ever required to read information from it.

Please update the firmware to sleep the OLED display until a button is pressed.  The display can then remain active for a period before sleeping again (15-60 secs).  This can be an optional setting in the UI.

**Comment by rayshobby** [comment]
This is already in the current firmware, by setting Idle Brightness to 0.

**Comment by Nu11u5** [comment]
@rayshobby where in the UI is this?  I am unable to find it.

**Comment by rayshobby** [comment]
Edit Options -> LCD Screen -> Idle Brightness.

**Comment by Nu11u5** [comment]
Does this require a minimum firmware version?  My hardware is still running v2.1.9 (2).

![image](https://user-images.githubusercontent.com/617690/183311645-b1016fd0-4757-4f86-9668-bb2cbc6a7ea0.png)

**Comment by rayshobby** [comment]
I said 'current firmware', which means 2.1.9(9)

**Comment by Nu11u5** [comment]
Thanks I will attempt an update.

Are the release notes for 2.1.9 (9) on the release page cumulative since the last release?  The is not mention of previous releases since 2.1.8.

**Comment by Nu11u5** [comment]
I've completed the update to v2.1.9-r9 and set the idle brightness to the lowest value in the UI.  The OLED is dimming but is still lit.  Is this sufficient to prevent further burn-in?
