### ISSUE TITLE
[Feature Request] Provide user feedback on weather based watering 

### ISSUE THREAD

**Issue by arthurbenemann** [OpenSprinkler/OpenSprinkler-Firmware#214]
Currently  the webui does not seem to have any feedback on the weather based watering schedule. When setting-up Evapotranspiration (ETo) method it would be useful to have some sort of feedback on the current ETo index, either displaying current ETo or calculated watering percentage.

Possible places to provide the current ETo index or watering percentages would be:
- `/#sprinklers` page, next to water level or current weather
- `/#forecast` page, if historical or forecasted ETo index is available

**Comment by rayshobby** [comment]
What you are proposing is an app feature request, this is the firmware repository. You can repost this in the OpenSprinkler-App repository.
