### ISSUE TITLE
Since the change to the apple weather api water percentage and eTO calc are at 0

### ISSUE THREAD

**Issue by ecto1a2003** [OpenSprinkler/OpenSprinkler-Firmware#227]
weather service is routinely unavailable, water calc is at 0percent, recorded rain is a 0 percent, several other users are reporting the issue as well.

**Comment by rayshobby** [comment]
Hi first of all this is a weather bug it's not a firmware bug please report it at the opensprinkler-weather repo.  Second, we just switched to Apple Weatherkit as DarkSky is no longer available and we are aware ETo is not working properly. We will be fixing it this weekend. Thanks for your understanding. In the meantime you can temporarily switch to Zimmerman method.
