### ISSUE TITLE
mqtt api

### ISSUE THREAD

**Issue by foscoj** [OpenSprinkler/OpenSprinkler-Firmware#231]
Hi,

the mqtt only shows online/offline and after a reboot it does not switch to online immediately.

I see the mqtt-api branch, but it seems to be abandoned.

Are there any plans to implement a full mqtt api support?

At least for status and control of starting and stopping valves/programs would be great for UI and remote control button support.

Thanks!

**Comment by rayshobby** [comment]
The entire mqtt-api branch has been integrated into the latest firmware. We tested MQTT and everything is working as expected. Did you subscribe to a specific topic or have you tried to subscribe to wildcard?

**Comment by foscoj** [comment]
I tried to inspect the data with the MQTT Explorer, MQTT Snooper on android results in the same view.
I am on a wired connection with the 3.2 AC Hardware.
MQTT integration is enabled to a mosquitto on raspberry without authentication.
<img width="149" alt="image" src="https://github.com/OpenSprinkler/OpenSprinkler-Firmware/assets/8149512/b17d86ee-d149-4a82-a0dc-39765db26c65">
<img width="344" alt="image" src="https://github.com/OpenSprinkler/OpenSprinkler-Firmware/assets/8149512/735ca0aa-fc09-4d11-b8d1-4aaffbfe5ed4">

**Comment by foscoj** [comment]
ah, when I activate a station, a mqtt message is available. But it stays online with JSON content.
It seems to be, that the REST API principles are used for mqtt communication, this is a little bit strange ;)

**Comment by foscoj** [comment]
ok, so it is json notifications in mqtt currently.

thanks, but not really what I expected :(

**Comment by rayshobby** [comment]
If you want to change it to other formats, you can modify the firmware yourself. The MQTT feature was implemented by other developers and they had a reason to implement it in JSON format.
