### ISSUE TITLE
Unreachable MQTT Broker Causes Opensprinkler Firmware to Stall

### ISSUE THREAD

**Issue by RotorMotor42** [OpenSprinkler/OpenSprinkler-Firmware#234]
If MQTT is enabled and the broker is not reachable OS freezes until a timeout occurs.
This causes lockups that can last for more than 2 minutes.
During that time the UI is unresponsive and the valves are not operated.

This behavior was observed in strace.

**Comment by rayshobby** [comment]
The MQTT library (pubsubclient.h) defines the connection timeout to be 15 seconds by default, and the firmware will make 3 attempts just for reliability. Both can be lowered obviously, if the MQTT server is frequently offline:
https://github.com/knolleary/pubsubclient/blob/master/src/PubSubClient.h#L36
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/master/mqtt.cpp#L496

But honestly if the MQTT server is offline, there will have to be some amount of timeout, at least a few seconds. I am closing this issue for now as exactly how long the timeout should be is more of a personal preference.
