### ISSUE TITLE
OSPI not providing username and password to the MQTT broker 2.2.0((1)

### ISSUE THREAD

**Issue by joeracer321** [OpenSprinkler/OpenSprinkler-Firmware#236]
OSPI will not connect to my HomeAssistant MQTT broker. The broker reports an error "error: received null username or password for unpwd check" The broker address, port, username and password are all correct in the OpenSprinkler settings menu.

**Comment by rayshobby** [comment]
I've just tested this and I can't reproduce this issue. Tried it on both RPi 4 and 5 with a MQTT broker configured with user name and password. Both worked as expected. You can pull from the latest repo and if the issue still persists you can reopen this issue.
