### ISSUE TITLE
Feature: Provide sensor input and start programs via MQTT

### ISSUE THREAD

**Issue by Vrumfondel** [OpenSprinkler/OpenSprinkler-Firmware#239]
Hi there,

It would be a very good feature to have MQTT inputs to OpenSprinkler via MQTT.
For example an option to send rain status via MQTT instead of wiring a sensor would be great, inputing humidity sensors via MQTT or just triggering the start of a program.

**Comment by mabe42** [comment]
I do support this feature request. I do have plants in pots on southerly oriented balcony and terrasse which require water more often than the rest of the garden. Additionally I have DIY soil humidity sensors and I am running mosquitto already. Wired sensors are a no-go in my situation. Therefore, I would also like to have the possibility to switch individual circuits/programs depending on MQTT messages.
