### ISSUE TITLE
Add "context" to app URL

### ISSUE THREAD

**Issue by therevoman** [OpenSprinkler/OpenSprinkler-Firmware#24]
I have multiple web apps running on the same RPi, and would like to use the same hostname and port to run them.  Would it be possible to add something to the path to isolate the opensprinkler app?

Right now I access it with
http://mypi:8080/

I would like to access it, and all helper apps with something like
http://mypi:8080/opensprinkler

**Comment by salbahra** [comment]
You are welcome to use any other port (ex: 9090) for OpenSprinkler and a different port for every other service you want to host on your RPi. Afterwards, you can host an Apache proxy for all the services running on port 8080 and redirecting each service to the subdirectory.

Example:
ProxyPass /opensprinkler/ http://mypi:9090/
ProxyPassReverse /opensprinkler/ http://mypi:9090/
