### ISSUE TITLE
Unusual DNS requests originating from opensprinkler

### ISSUE THREAD

**Issue by phoenix-9** [OpenSprinkler/OpenSprinkler-Firmware#264]
I was looking at tcpdump and noticed some unusual DNS queries originating from Opensprinkler:

11:16:51.637539 IP 192.168.17.19.61815 > 192.168.17.1.53: 1866+ A? M-DQ>^Cx^Ds^D^G^B3^E.dat. (34)
...
11:17:21.685907 IP 192.168.17.19.61815 > 192.168.17.1.53: 1867+ A? M-DQ>^Cx^Ds^D^G^BM-S^D.dat. (34)

These are invalid ("dat" is not a TLD), and probably indicate the presence of some other error in the code.

Firmware 2.2.0 (3)
Hardware 3.2 - AC

Let me know if you need more information.

**Comment by arfrie22** [comment]
This should be fixed with #287, if this issue still persists after the next firmware update, 2.2.1. Please reopen the issue.
