### ISSUE TITLE
Scheduling is not working if WIFI is down

### ISSUE THREAD

**Issue by pirracas77** [OpenSprinkler/OpenSprinkler-Firmware#265]
Hello:

I realize that scheduling is not starting if the wifi is down. What is the reason behind this behaviour? Is there anyway to avoid this problem?

This is my version:

![image](https://github.com/OpenSprinkler/OpenSprinkler-Firmware/assets/18216098/c5490c8c-3099-4577-8bed-f5f406b4a29c)

**Comment by rayshobby** [comment]
I can't reproduce this problem. I unplugged my WiFi router and the programs still start just fine.
