### ISSUE TITLE
"The request was too large" error on reboot

### ISSUE THREAD

**Issue by adepiero** [OpenSprinkler/OpenSprinkler-Firmware#292]
OSPI compiled on Raspberry Pi Zero with bullseye.
After a system reboot I cannot connect to Opensprinkler lan server, The web page just replies "The request was too large", withouth even asking for authentication. If I restart OSPI service with `sudo systemctl restart OpenSprinkler.service`, it works.
I am connecting directly to OSPI, no proxies are involved. I receive the same error both with MS Edge and Firefox. I tried to clear the browsers' history, it doesn't work.

**Comment by rayshobby** [comment]
We believe we've fixed this issue with the latest update. It's a startup script issue, as the firmware started running before the network was available. We've now changed the startup script to use systemd which allows starting the firmware after network is available. Please update the firmware and check if it works for you. Please note that we've changed the startup script from using init.d to systemd. So in case any problem comes up, just keep this in mind.

**Comment by adepiero** [comment]
It works not, thank you.
The new script moved successfully my configuration from init.d to system, thank you!

**Comment by psmedley** [comment]
I installed the latest firmware this morning and rebooted my pi zero. Unfortunately I still got the 'request too large' message. I'll investigate more this evening.

**Comment by rayshobby** [comment]
We pushed in the fix just 1 hour ago:
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/commits/master/
the fix wasn't there this morning.

**Comment by psmedley** [comment]
I'm in Australia, it's 7:15am here. I pulled the code after you posted about it here.

**Comment by mwerski** [comment]
Unfortunately this fix does not work for me - still the exact same symptom.

**Comment by rayshobby** [comment]
Could you please report some details of your hardware? Like which RPi hardware, which Raspbian version? We need some details in order to reproduce the issue.

**Comment by mwerski** [comment]
Sure! It is a model 3, connected via internal ethernet (DHCP), more precisely it is a UniPi Neuron S103 (but that should not matter in regards to network stuff) running on Debian Buster. Please drop me a note if you need more information.

`root@opensprinkler:/usr/local/OpenSprinkler-Firmware# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
root@opensprinkler:/usr/local/OpenSprinkler-Firmware# lshw
opensprinkler
    description: ARMv7 Processor rev 4 (v7l)
    product: Raspberry Pi 3 Model B Rev 1.2
    serial: 000000005ba6452c
    width: 32 bits
    capabilities: smp
  *-core
       description: Motherboard
       physical id: 0
     *-cpu:0
          description: CPU
          product: cpu
          physical id: 0
          bus info: cpu@0
          size: 700MHz
          capacity: 700MHz
          capabilities: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 cpufreq
     *-cpu:1
          description: CPU
          product: cpu
          physical id: 1
          bus info: cpu@1
          size: 700MHz
          capacity: 700MHz
          capabilities: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 cpufreq
     *-cpu:2
          description: CPU
          product: cpu
          physical id: 2
          bus info: cpu@2
          size: 700MHz
          capacity: 700MHz
          capabilities: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 cpufreq
     *-cpu:3
          description: CPU
          product: cpu
          physical id: 3
          bus info: cpu@3
          size: 700MHz
          capacity: 700MHz
          capabilities: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32 cpufreq
     *-memory
          description: System memory
          physical id: 4
          size: 923MiB
  *-usbhost
       product: DWC OTG Controller
       vendor: Linux 5.10.103-v7+ dwc_otg_hcd
       physical id: 1
       bus info: usb@1
       logical name: usb1
       version: 5.10
       capabilities: usb-2.00
       configuration: driver=hub slots=1 speed=480Mbit/s
     *-usb
          description: USB hub
          product: SMC9514 Hub
          vendor: Standard Microsystems Corp.
          physical id: 1
          bus info: usb@1:1
          version: 2.00
          capabilities: usb-2.00
          configuration: driver=hub maxpower=2mA slots=5 speed=480Mbit/s
        *-usb:0
             description: Ethernet interface
             product: SMSC9512/9514 Fast Ethernet Adapter
             vendor: Standard Microsystems Corp.
             physical id: 1
             bus info: usb@1:1.1
             logical name: eth0
             version: 2.00
             serial: b8:27:eb:a6:45:2c
             size: 100Mbit/s
             capacity: 100Mbit/s
             capabilities: usb-2.00 ethernet physical tp mii 10bt 10bt-fd 100bt 100bt-fd autonegotiation
             configuration: autonegotiation=on broadcast=yes driver=smsc95xx driverversion=5.10.103-v7+ duplex=full firmware=smsc95xx USB 2.0 Ethernet ip=192.168.0.16 link=yes maxpower=2mA multicast=yes port=twisted pair speed=100Mbit/s
        *-usb:1
             description: Human interface device
             product: USB2IIC_CTP_CONTROL
             vendor: wch.cn
             physical id: 2
             bus info: usb@1:1.2
             version: 0.00
             capabilities: usb-0.01
             configuration: driver=usbhid maxpower=64mA speed=12Mbit/s
  *-network
       description: Wireless interface
       physical id: 2
       logical name: wlan0
       serial: b8:27:eb:f3:10:79
       capabilities: ethernet physical wireless
       configuration: broadcast=yes driver=brcmfmac driverversion=7.45.98 firmware=01-8e14b897 multicast=yes wireless=IEEE 802.11
root@opensprinkler:/usr/local/OpenSprinkler-Firmware# git log
commit 52889c8fd12a57997f6ff35665717795e5270fe8 (HEAD -> master, origin/master, origin/HEAD)
Merge: e336eb0 4f194d5
Author: Ray <rayshobbyshop@gmail.com>
Date:   Tue Jul 30 11:36:19 2024 -0400

    Merge pull request #297 from OpenSprinkler/debug-build

    Add an option in the build script to enable debug

commit 4f194d570a602d079dcd2b0d4102a39a7c6f1c81 (origin/debug-build)
Author: arfrie22 <43021241+arfrie22@users.noreply.github.com>
Date:   Tue Jul 30 10:03:43 2024 -0400

    debug build

commit e336eb0d1b4d354d256222d4f3623cdf87fdbeae
Merge: 70ee32a f4d3caa
Author: Ray <rayshobbyshop@gmail.com>
Date:   Mon Jul 29 15:32:42 2024 -0400

    Merge pull request #295 from OpenSprinkler/systemd-startup

    Systemd startup

commit f4d3caafe989697e9451aa0e762df3a727a40dc1 (origin/systemd-startup)
Author: arfrie22 <43021241+arfrie22@users.noreply.github.com>
Date:   Mon Jul 29 11:19:21 2024 -0400

    fix build script

commit 3356cf5a5a20119b37136c748af190d92d0a932f
Author: arfrie22 <43021241+arfrie22@users.noreply.github.com>
Date:   Mon Jul 29 11:18:10 2024 -0400

    update remove

commit 88fdc7ed53000629d8eea14e91654b111d9f2d54
Author: arfrie22 <43021241+arfrie22@users.noreply.github.com>
Date:   Mon Jul 29 11:16:36 2024 -0400

    update build script to remove old initd

commit 35812f28f7fd9f71293b57e989f202b3d5b5dc9b
Author: arfrie22 <43021241+arfrie22@users.noreply.github.com>
Date:   Mon Jul 29 11:03:59 2024 -0400

    add update to gitignore

commit 04c89f9af0f5345598000200fa519ca55a8c17d4
Author: arfrie22 <43021241+arfrie22@users.noreply.github.com>
Date:   Mon Jul 29 11:03:35 2024 -0400

...skipping...
Author: Rayshobby <rayshobbyshop@gmail.com>
Date:   Mon Sep 15 23:53:14 2014 -0400

    removed wtscale; weather scale is now directly assigned to wl variable; added support to push new stations (to be scheduled) behind currently scheduled stations

commit 342399bed28daa207127466f916117913c7e54be
Author: Rayshobby <rayshobbyshop@gmail.com>
Date:   Mon Sep 15 11:33:00 2014 -0400

    fixed program name (when name is not give or is empty in /cp command); fixed station disable bits

commit 60ce46ff1555daa905521af4a4afcd22c21bcd53
Author: Rayshobby <rayshobbyshop@gmail.com>
Date:   Fri Sep 12 16:36:55 2014 -0400

    fixed logging issue; added back runonce support; wired in weather script, /jc page now has three more variables: 'sunrise', 'sunset', 'wtscale'

commit fe219ba2bb42c7ad9b9e8e2241adc2964fd5f1c7
Author: Rayshobby <rayshobbyshop@gmail.com>
Date:   Fri Sep 12 10:51:28 2014 -0400

    modified weather script to support json output, by adding &format=json in the query

commit 34057304049c3feaf0ec8eff1e3181b03c0ec18f
Author: Rayshobby <rayshobbyshop@gmail.com>
Date:   Fri Sep 12 10:21:14 2014 -0400

    add weather1.py, Zimmerman algorithm

commit 453515de65b63b8e3484dd07c0870cf7204d7538
Author: Rayshobby <rayshobbyshop@gmail.com>
Date:   Fri Sep 12 10:14:42 2014 -0400

    added support to accept empty API key

commit 24bdcada10c8d16bd9aa43dbc716368ead139228
Author: Rayshobby <rayshobbyshop@gmail.com>
Date:   Thu Sep 11 19:31:15 2014 -0400

    changed station delay time to use the 8-bit comrpessed representation. firmware change only, UI will pass in/out uncompressed value (in units of seconds)

commit cdc12a67b8893d42ac5b2b4cd05298a18af636b9
Author: Rayshobby <rayshobbyshop@gmail.com>
Date:   Thu Sep 11 18:43:40 2014 -0400

    initial check in of firmware 2.1.0 Arduino code

commit 333bc85de44ae1c07302685d4ecf355ce344e26c
Author: Ray <rayshobbyshop@gmail.com>
Date:   Thu Sep 11 18:17:22 2014 -0400

    Initial commit
root@opensprinkler:/usr/local/OpenSprinkler-Firmware#`

**Comment by arfrie22** [comment]
I have found where the bug was happening, the request was not handling errors properly, I have now fixed that. If this still doesn't work, please re-open this issue.

**Comment by psmedley** [comment]
Confirming this resolves the issue for me.

**Comment by mwerski** [comment]
Same here, issue resolved.
