### ISSUE TITLE
The “else” is executed even if not ARDUINO

### ISSUE THREAD

**Issue by booboodoguy** [OpenSprinkler/OpenSprinkler-Firmware#299]
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/52889c8fd12a57997f6ff35665717795e5270fe8/EMailSender.h#L43

**Comment by rayshobby** [comment]
Please use the build.sh script or the make file. This file is NOT in the build script source file if you are compiling under Linux.
