### ISSUE TITLE
Provide feedback about the internals of the watering level calculation

### ISSUE THREAD

**Issue by wernerdaehn** [OpenSprinkler/OpenSprinkler-Firmware#318]
I have set weather adjustment method to Zimmerman and the current watering level is 38%. Fine, it was sunny but not too hot and rain is expected.
But what caused the level of 38%? What information is used and what is the decision tree?

Currently it is a black box. Hence providing more information in the Systems Diagnostics would be a good idea.

![image](https://github.com/user-attachments/assets/27d5f655-e439-4f25-9ba2-879e5503192c)

**Comment by rayshobby** [comment]
Details are explained here:
https://openthings.freshdesk.com/support/solutions/articles/5000823370-using-weather-adjustments
