### ISSUE TITLE
How add new climate restrictions?

### ISSUE THREAD

**Issue by matteocostantini** [OpenSprinkler/OpenSprinkler-Firmware#319]
How add new climate restrictions in my ospi?

i find only california, without edit this list and every  proproperty

**Comment by rayshobby** [comment]
The firmware itself doesn't calculate weather, but you can modify the OpenSprinkler weather script:
https://github.com/OpenSprinkler/OpenSprinkler-Weather
For that reason this issue should be moved to that repository.

What restrictions do you want to implement?
