### ISSUE TITLE
Feature request: Manual program run should allow for time adjustment

### ISSUE THREAD

**Issue by djabi** [OpenSprinkler/OpenSprinkler-Firmware#35]
Currently manual program run always runs the program at 100%. It will be nice to allow specifying run time adjustment or using the current weather data. 

The use case: I have program scheduled to run 30 minutes after sunset. Yesterday, just after the program started the two puppies decided to go outside for evening routine so I had to stop the program. When I then manually run the program I couldn't run it as it was about to run with the weather data. I had to start the program at 100%.

**Comment by rayshobby** [comment]
The best solution is to set a program for your manual run schedule, and set the program to 'disabled'. This way the program won't run automatically, but you can run it manually, and when you run it, the app / UI will prompt you whether you want to apply today's watering percentage.
