### ISSUE TITLE
Feature request: Allow postponing the current program for certain time

### ISSUE THREAD

**Issue by djabi** [OpenSprinkler/OpenSprinkler-Firmware#36]
It will be nice to allow pausing temporary the current program. For example "pause for 30mins or pause for 1h".

The use case: When the program is in progress sometimes there is a need to temporary postpone the program and later resume the program. I have two puppies that "use" the backyard from time to time. When the program is currently in progress I can only cancel the current program. I need to remember to latter run the program. It is also not possible to run the program manually with weather data (I have open separate feature request for this too).

**Comment by rayshobby** [comment]
This is being considered for the next firmware update (not the upcoming 2.1.7 but the next one). I've figured out a way to implement this in firmware, but there won't be enough time to add it to 2.1.7.
