### ISSUE TITLE
Guidance for wiring 433mhz transmitter to beaglebone

### ISSUE THREAD

**Issue by xaque208** [OpenSprinkler/OpenSprinkler-Firmware#37]
I've seen the doc for wiring up a transmitter to the standard opensprinkler board.  Are there similar docs for wiring up a beaglebone so that the program is able to send the required signals for operating remote switches?  Any guidance here would be appreciated.

**Comment by rayshobby** [comment]
The transmitter has three pins: VCC/VIN goes to +5V, GND goes to GND, and DAT goes to the data pin (which is GPIO 51 by default in the firmware):
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/master/defines.h#L334

**Comment by xaque208** [comment]
Excellent, thank you.
