### ISSUE TITLE
Send Log via email

### ISSUE THREAD

**Issue by chrauscher** [OpenSprinkler/OpenSprinkler-Firmware#38]
It would be great if I get notified via email when a log entry is added (including the log). So I get notified if a program was executed

Aditionally it would be great to get informed when a program is postponed because of rain delay.

**Comment by rayshobby** [comment]
This will be mostly supported in the upcoming firmware 2.1.7, which has added support for IFTTT notifications. Specifically, you can set an IFTTT recipe to send notifications to you email or text message, all data logged on openSprinkler are also sent out as IFTTT notifications, this way, you essentially receive the same log data through email.
