### ISSUE TITLE
Build error for BeagleBone

### ISSUE THREAD

**Issue by xaque208** [OpenSprinkler/OpenSprinkler-Firmware#40]
I've attempted to update the software on my beagle bone for the first time in a while.  I get the following error.  Let me know if I can provide more detail.

```
[root@sprink1 /usr/src/opensprinklergen2]$ ./build.sh osbo
Building OpenSprinkler...
server.cpp: In function 'byte server_change_stations(char*)':
server.cpp:494:25: error: 'PIN_FREE_LIST' was not declared in this scope
       byte gpioList[] = PIN_FREE_LIST;
                         ^
Done!
[root@sprink1 /usr/src/opensprinklergen2]$ git rev-parse HEAD
09c33ec33277e2a57aca84168ac72408168dd58d
```

**Comment by rayshobby** [comment]
hi, this is because PIN_FREE_LIST is not defined in defines.h for OSBO. We will fix this in the next update. For now you can go to defines.h and just add
#define PIN_FREE_LIST {}
in the OSBo section
