### ISSUE TITLE
24 hour time setting

### ISSUE THREAD

**Issue by hsleewis** [OpenSprinkler/OpenSprinkler-Firmware#41]
I would love to be able to set the time to a 24 hour clock instead of AM/PM. :-)

**Comment by rayshobby** [comment]
Hi, this is mainly a UI/app request since the only place where the firmware displays time on the controller itself is the LCD display of time. Assuming you mostly use the app / web UI, the 24 vs 12 hour clock issue should be solved there. I have added this request to app todo list.
