### ISSUE TITLE
Link in Wunderground api field help text points to old support

### ISSUE THREAD

**Issue by frob** [OpenSprinkler/OpenSprinkler-Firmware#46]
The link in the help text for the wunderground api field points to opensprinkler support. It should point to openthings support.

**Comment by salbahra** [comment]
I believe you are referring to the link posted on this article: https://openthings.freshdesk.com/support/solutions/articles/5000017312-using-weather-adjustments. I went ahead and updated the link to point to: https://openthings.freshdesk.com/support/solutions/articles/5000017485

Thank you for your report!
