### ISSUE TITLE
Docker container for OpenSprinkler on RPi

### ISSUE THREAD

**Issue by JohnStrunk** [OpenSprinkler/OpenSprinkler-Firmware#50]
I've been running OSPi using docker for a while, and I'm interested in sending a PR to get the Dockerfile into the main repo.

I'd like to get the log dir and NVM files into a proper docker volume. Currently, I have to do some symlink ugliness in the docker image because OpenSprinkler insists on writing its data files into the same directory as the executable due to get_runtime_path() and get_filename_fullpath().

My current idea is to get rid of the get_filename_fullpath calls and just do a chdir(datadir) in main(). This would allow a datadir to be passed in on the command-line or by default, have datadir=get_runtime_path().

Thoughts?

**Comment by kpfleming** [comment]
This sounds like a good idea, even for non-Docker usage.

**Comment by xaque208** [comment]
I'm on beagle.

**Comment by frob** [comment]
I would use this.

**Comment by Cabalist** [comment]
I would also use this.   It would be great to see this merged.

**Comment by xaque208** [comment]
I've since purchased the new esp8266 platform and haven't looked back.    I'm still not sure the utility of this, since you'll need to interface with the GPIO, and passing that through the container, while perhaps possible, might be fragile.
