### ISSUE TITLE
Can't specify interface to bind server to

### ISSUE THREAD

**Issue by ghulands** [OpenSprinkler/OpenSprinkler-Firmware#60]
It would be good if you can specify which interface to bind to so you can bind to localhost and then put an nginx ssl proxy in front of it. As it is now, you have to block the 8080 port via iptables.

**Comment by ghulands** [comment]
For those interested

iptables -A INPUT ! -s 127.0.0.1 -p tcp -m tcp --dport 8080 -j DROP

**Comment by kpfleming** [comment]
For completeness, I'd use `! -i lo` there instead of `! -s 127.0.0.1`.

**Comment by davidjb** [comment]
@rayshobby Was this added to the firmware?
