### ISSUE TITLE
GET requests should be stateless

### ISSUE THREAD

**Issue by gdaniels13** [OpenSprinkler/OpenSprinkler-Firmware#61]
I was looking through the api documentation and I noticed that all the documented commands are GET requests.  This brought to mind [this](https://twitter.com/rombulow/status/990684463007907840) anecdote about a similar circumstance.

The api should be redesigned to follow the best practices of REST. eg stateless and don't change state with a get request.

**Comment by rayshobby** [comment]
This will be addressed in the next firmware where we will change to use POST. For backward compatibility of firmware, we are still using GET at the moment.
