### ISSUE TITLE
Weather forcast is showing the wrong date

### ISSUE THREAD

**Issue by frob** [OpenSprinkler/OpenSprinkler-Firmware#64]
![image](https://user-images.githubusercontent.com/316176/40565301-d3e0fdec-6020-11e8-8135-67aa73a3ea0d.png)

I am not sure why, but when I click on it it shows from Jan.

**Comment by rayshobby** [comment]
This is a UI/app related issue, and not a firmware issue. I am closing it for this repository but you can open it in the OpenSprinkler-App repository.
