### ISSUE TITLE
Build error..

### ISSUE THREAD

**Issue by Neomancer86** [OpenSprinkler/OpenSprinkler-Firmware#65]
On a Raspberry Pi 3... getting 

pi@OpenSprinkler:/usr/local/OpenSprinklerGen2 $ sudo ./build.sh ospi
Building OpenSprinkler...
gpio.cpp: In function ‘void attachInterrupt(int, const char*, void (*)())’:
gpio.cpp:411:14: error: ‘delay’ was not declared in this scope
       delay(1) ;
              ^

**Comment by Neomancer86** [comment]
i believe this is related to rays commit: 

https://github.com/OpenSprinkler/OpenSprinkler-Firmware/pull/62/commits/f516d9bb59b6604e43ea363e5357f9079bc7432a

**Comment by rayshobby** [comment]
The compilation error has been resolved.

**Comment by Neomancer86** [comment]
yes thanks. although i think there is another issue now related to that -  discussion on the forums regarding the configuration can't be edited.

**Comment by rayshobby** [comment]
See my comment: https://github.com/OpenSprinkler/OpenSprinkler-Firmware/issues/67

**Comment by Neomancer86** [comment]
perfect. thanks!
