### ISSUE TITLE
Use GPIOs 4,17,21,22 as out for zones

### ISSUE THREAD

**Issue by a-reda** [OpenSprinkler/OpenSprinkler-Firmware#82]
I’m trying to install OpenSprinkler firmware on GreenIQ hardware (It consists of a RPi 1 A and a relay board connecting to the valves). I detected, by using WiringPi gpio tool, the valves corresponding to each GPIO.

My problem is that OpenSprinkler Firmware uses some of them (4,17,21,22) for latch,data,clock,output_enable. Is there a possibility to use them for GPIO OUT? If so how? and what would I lose ?

**Comment by gargamelonly** [comment]
Have you succeeded in adapting and using OpenSprinkler on the GreenIQ hardware?
