### ISSUE TITLE
RF station pulse length value ignored; default value used instead

### ISSUE THREAD

**Issue by mark-bom** [OpenSprinkler/OpenSprinkler-Firmware#83]
This issue relates to setting up RF stations on a recently purchased OS 3.0 (AC powered) unit.

For an RF station, the on/off codes and pulse length are set by entering a 16 digit hex value in station setup; the last 4 digits being the pulse length.

However, the pulse length parameter is effectively ignored; instead the rc_switch library default value of 350 microseconds is always used by OpenSprinkler.  Testing using the rc_switch example, ReceiveDemo_Advanced, confirmed this.

I think the issue is lines 1384 and 1385 in OpenSprinkler.cpp:
.             1384   rfswitch.setPulseLength(length);
.             1385   rfswitch.setProtocol(1);

The setProtocol function call,  effectively re-sets the pulse length back to the default of 350 microseconds, over-riding the prior setPulseLength call.

Two solution options are suggested.  Firstly, reverse the two lines of code (set the length after setting the protocol).  Secondly, combine the lines of code using the setProtocol variant that includes pulse length in the same call:
.        rfswitch.setProtocol(1, length);

This issue has been replicated, and both solutions  tested, using the rc_switch examples, SendDemo and ReceiveDemo_Advanced.  Note that this same issue was present, and has been fixed, in the SendDemo example.

Mark

**Comment by rayshobby** [comment]
Yes, I became aware of the issue a few months ago while debugging this for a user. The fix is by setting pulselength after setting protocol. I've already made this change in 2.1.8 minor revision (3):
https://github.com/OpenSprinkler/OpenSprinkler-Firmware/blob/dev-218.3/OpenSprinkler.cpp#L1413
it should be pulled to the main branch shortly.

Thanks.
