### ISSUE TITLE
OS3.0 fails to reconnect to WIFI

### ISSUE THREAD

**Issue by Hambootje** [OpenSprinkler/OpenSprinkler-Firmware#88]
My OS3.0 is often disconnecting from WIFI. I see many systems reboots where the device come back online again, but occasionly the display reads "connecting...." but nothing happens. A power cycle fixes the problem.

Setting the IP to a static address does not help.

It seems I'm not the ony one suffering from this problem:
[https://opensprinkler.com/forums/topic/my-open-sprinkler-has-been-having-trouble-connecting-lately/](url)

**Comment by rayshobby** [comment]
I don't think this is a firmware problem -- we have several test OS 3.0s on our WiFi and none of them has any connection issue. I believe this has to do with the compatibility of the WiFi chip and your specific router. We can certainly modify the firmware to trigger a reboot if the controller has been disconnected to a while, to simulate a manual power cycle, but this is not the source of the disconnection issue.
