### ISSUE TITLE
Master Off Adjustment cannot be set

### ISSUE THREAD

**Issue by traylenator** [OpenSprinkler/OpenSprinkler-Firmware#94]
Firmware 2.1.8 (3)

Hi,

While `Master On Adjustment` can be set via web interface and is saved correctly.
If you try and set `Master Off Adjustment` it is never saved and the value is always returned back to 0.

Steve

**Comment by rayshobby** [comment]
Master off must be a negative value. Did you make sure of that?

**Comment by traylenator** [comment]
Indeed negative values are  saved - thanks.
